services:
  - type: web
    name: videoconf-reservas
    env: docker
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:63sY4C2Oa3s5fJ+LWnAMmOHjw6mdm4JxU2ZmqIdzdJs=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: "VideoConf Reservas"
      - key: MAIL_TO_ADDRESS
        sync: false